### PR TITLE
test: wrap tempfile() and tempdir() in normalizePath()

### LINKED ISSUE #235: temporary files and directories don't match on macOS
Various tests are failing on macOS, all with similar errors:

```r
test-get-path-from-object.R:41: failure: get_model_path() finds .mod path
get_model_path(mod) not identical to `temp_mod`.
1/1 mismatches
x[1]: "/private/var/folders/d3/x8vvcfl93bzdqyjldg5kj6cr0000g
x[1]: p/T/RtmpHa7Y1M/file45e2210917f9.mod"
y[1]: "/var/folders/d3/x8vvcfl93bzdqyjldg5kj6cr0000gp/T/Rtmp
y[1]: Ha7Y1M/file45e2210917f9.mod"
```

In each case, the failure occurs because the result refers to `/private/foo/bar` and the expectation to `/foo/bar`. This is a consequence of the fact that `/tmp` and `/var` are symlinks on macOS. From `?normalizePath`:

> For example, on macOS absolute paths such as ‘/tmp’ and ‘/var’ are symbolic links.

In particular, they are symlinks into `/private`:

```sh
➜  ~ uname
Darwin
➜  ~ ls -ld /tmp /var
lrwxr-xr-x@ 1 root  admin  11 Apr  6  2020 /tmp -> private/tmp
lrwxr-xr-x@ 1 root  admin  11 Apr  6  2020 /var -> private/var
```

But `tempdir()` is not guaranteed to return a canonical path:

> On a Unix-alike, the value will be an absolute path (unless tmpdir is set to a relative path), but it need not be canonical (see normalizePath) and on macOS it often is not.

Thus, any path that goes through `normalizePath()` will be canonical, e.g., include `/private`, and paths that do not, will not necessarily be canonical. We do not observe this behavior on Ubuntu because `/var` and `/tmp` are not symlinks.

To resolve this, we should ensure that calls to `tempfile()` or `tempdir()` in our tests are wrapped in `normalizePath()`, at least the ones that are run on macOS.

### PR DESCRIPTION
**Pull request by copernican**
Closes #235.

### CODE REVIEW

File: tests/testthat/test-submit-model.R [hunk 1]
```diff
@@ -61,6 +61,7 @@ test_that("submit_model(.dry_run=T) with bbi_nonmem_model object parses correctl
 test_that("submit_model() creates correct call for non-NULL .config_path", {
   temp_config <- tempfile(fileext = ".yaml")
   readr::write_file("foo", temp_config)
```
Comment (seth127) [inline tests/testthat/test-submit-model.R:63]: shouldn't the `normalizePath` be _above_ the `write_file` call? Is there a reason you don't just do 
```
temp_config <- normalizePath(tempfile(fileext = ".yaml"))
```
?

File: tests/testthat/test-submit-models.R [hunk 2]
```diff
@@ -118,6 +118,7 @@ withr::with_options(list(rbabylon.bbi_exe_path = "bbi"), {
   test_that("submit_models() works with non-NULL .config_path", {
     temp_config <- tempfile(fileext = ".yaml")
     readr::write_file("foo", temp_config)
+    temp_config <- normalizePath(temp_config)
```
Comment (seth127) [inline tests/testthat/test-submit-models.R:121]: same as above

**Review by seth127 — APPROVED** [review]
This passes on my Mac so it's approved. I am a little confused about that `temp_config` call I commented on, but I guess that's my bad.

File: tests/testthat/test-submit-model.R (hunk 1 above)
Comment (copernican) [reply tests/testthat/test-submit-model.R:63]: The call to `normalizePath()` must happen after `write_file()`, because the path given by `temp_config()` does not exist until after that. `tempfile()` does not _create_ a file, but rather returns

> a character vector giving the names of possible (temporary) files. Note that no files are generated by tempfile.

Thus, calling `normalizePath(tempfile())` will raise a warning, because the temporary file does not yet exist. But, after we write to it (or otherwise create it), it will exist, and `normalizePath()` will work as intended.

```r
x <- tempfile()
x
#> [1] "/var/folders/d3/x8vvcfl93bzdqyjldg5kj6cr0000gp/T//RtmplPceD2/file591b28bc8217"
normalizePath(x)
#> Warning in normalizePath(x): path[1]="/var/folders/d3/
#> x8vvcfl93bzdqyjldg5kj6cr0000gp/T//RtmplPceD2/file591b28bc8217": No such file or
#> directory
#> [1] "/var/folders/d3/x8vvcfl93bzdqyjldg5kj6cr0000gp/T//RtmplPceD2/file591b28bc8217"
file.exists(x)
#> [1] FALSE
writeLines("foo", x)
normalizePath(x)
#> [1] "/private/var/folders/d3/x8vvcfl93bzdqyjldg5kj6cr0000gp/T/RtmplPceD2/file591b28bc8217"
```
